defaults: &defaults
  app_name: deals
  org: TW-org
  is_service: true
  dependencies:
    - pricing

test:
  <<: *defaults
  space: test

staging:
  <<: *defaults
  space: staging

production:
  <<: *defaults
  space: production

new:
  app_name: deals
  org: idiots
  is_service: true
  space: test
  api: api.system.tw-ael.net
  skip_ssl: true
  app_domain: apps.tw-ael.net
  dependencies:
    - pricing
