defaults: &defaults
  app_name: deals
  org: TW-org
  is_service: true
  dependencies:
    - pricing

test:
  <<: *defaults
  space: test

staging:
  <<: *defaults
  space: staging

production:
  <<: *defaults
  space: production
